development:
  elasticsearch: 'http://localhost:9200'
  connect: 'http://localhost:8080'
  connect_url: 'http://localhost:8080'
  base: ""
test:
  elasticsearch: 'http://localhost:9200'
  connect: 'http://localhost:8080'
  connect_url: 'http://localhost:8080'
  base: ""
homolog:
  elasticsearch: 'http://jb048.jbrj.gov.br/elasticsearch'
  connect: 'http://jb048.jbrj.gov.br/connect'
  connect_url: 'http://jb048.jbrj.gov.br/connect'
  base: "/download_csv"
production:
  elasticsearch: 'http://cncflora.jbrj.gov.br/elasticsearch'
  connect: 'http://cncflora.jbrj.gov.br/connect'
  connect_url: 'http://cncflora.jbrj.gov.br/connect'
  base: "/download_csv"
